import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { NotificationType, Notification, Role, User } from "@/types";
import { DEFAULT_NOTIFICATION_SETTINGS, sendClientEmail, fetchUserNotifications } from "@/src/lib/services";

// All 17 notification types in Warevo
const ALL_NOTIFICATION_TYPES: NotificationType[] = [
  "NEW_ORDER",
  "ORDER_ISSUED",
  "PROCESSING_STARTED",
  "READY_FOR_DISPATCH",
  "ORDER_DISPATCHED",
  "CLIENT_RECEIVED_ORDER",
  "CLIENT_STARTED_VERIFICATION",
  "CLIENT_COMPLETED_VERIFICATION",
  "CLIENT_REJECTED_ORDER",
  "DAMAGE_REPORTED",
  "MISSING_ITEMS_REPORTED",
  "VERIFICATION_COMPLETED",
  "INVOICE_GENERATED",
  "INVOICE_SENT",
  "PAYMENT_RECEIVED",
  "PAYMENT_OVERDUE",
  "ORDER_COMPLETED",
];

describe("Notification Preferences Audit", () => {
  it("has exactly 17 notification event types defined in DEFAULT_NOTIFICATION_SETTINGS", () => {
    expect(Object.keys(DEFAULT_NOTIFICATION_SETTINGS).length).toBe(17);
    for (const eventType of ALL_NOTIFICATION_TYPES) {
      expect(DEFAULT_NOTIFICATION_SETTINGS[eventType]).toBeDefined();
    }
  });

  it("defaults ALL email preferences to OFF (clientEmail: false)", () => {
    for (const eventType of ALL_NOTIFICATION_TYPES) {
      const config = DEFAULT_NOTIFICATION_SETTINGS[eventType];
      expect(config.clientEmail).toBe(false);
      // inApp remains enabled by default for warehouse/client visibility
      expect(config.inApp).toBe(true);
    }
  });
});

describe("Notification Recipient Resolution and In-App Deduplication", () => {
  it("deduplicates identical notifications for the same event and order", async () => {
    const mockNotifs: Notification[] = [
      {
        id: "notif_1",
        tenantId: "tenant_1",
        userId: "user_1",
        orderId: "ord_1",
        type: "NEW_ORDER",
        title: "New Order Created",
        message: "Order has been created",
        priority: "normal",
        read: false,
        createdAt: "2026-09-25T10:00:00Z",
      },
      {
        id: "notif_2", // duplicate generated by duplicate contact selection
        tenantId: "tenant_1",
        userId: "user_1",
        orderId: "ord_1",
        type: "NEW_ORDER",
        title: "New Order Created",
        message: "Order has been created",
        priority: "normal",
        read: false,
        createdAt: "2026-09-25T10:00:01Z",
      },
      {
        id: "notif_3", // different user
        tenantId: "tenant_1",
        userId: "user_2",
        orderId: "ord_1",
        type: "NEW_ORDER",
        title: "New Order Created",
        message: "Order has been created",
        priority: "normal",
        read: false,
        createdAt: "2026-09-25T10:00:02Z",
      },
    ];

    // Deduplication logic test
    const seen = new Set<string>();
    const deduplicated: Notification[] = [];
    for (const n of mockNotifs) {
      const key = `${n.type || n.title}_${n.orderId || n.id}_${n.userId || ""}`;
      if (!seen.has(key)) {
        seen.add(key);
        deduplicated.push(n);
      }
    }

    expect(deduplicated.length).toBe(2);
    expect(deduplicated.map((n) => n.id)).toEqual(["notif_1", "notif_3"]);
  });

  it("filters broadcast notifications for client roles by clientId", () => {
    const notifications = [
      {
        id: "n1",
        tenantId: "t1",
        userId: null,
        orderId: "ord_client1",
        type: "ORDER_DISPATCHED" as NotificationType,
        title: "Order Dispatched",
        message: "Dispatched",
        priority: "normal",
        read: false,
        createdAt: "2026-09-25T10:00:00Z",
        order: { id: "ord_client1", clientId: "client_1" },
      },
      {
        id: "n2",
        tenantId: "t1",
        userId: null,
        orderId: "ord_client2",
        type: "ORDER_DISPATCHED" as NotificationType,
        title: "Order Dispatched",
        message: "Dispatched",
        priority: "normal",
        read: false,
        createdAt: "2026-09-25T10:00:00Z",
        order: { id: "ord_client2", clientId: "client_2" },
      },
    ];

    // Client 1 view: only see notifications for client_1
    const client1Notifs = notifications.filter((n) => n.order?.clientId === "client_1");
    expect(client1Notifs.length).toBe(1);
    expect(client1Notifs[0].id).toBe("n1");

    // Client 2 view: only see notifications for client_2
    const client2Notifs = notifications.filter((n) => n.order?.clientId === "client_2");
    expect(client2Notifs.length).toBe(1);
    expect(client2Notifs[0].id).toBe("n2");
  });
});

describe("Read / Unread Notification Status and Scoping", () => {
  it("correctly calculates unread count", () => {
    const list: Notification[] = [
      { id: "1", tenantId: "t1", type: "NEW_ORDER", title: "A", message: "", priority: "normal", read: false, createdAt: "" },
      { id: "2", tenantId: "t1", type: "NEW_ORDER", title: "B", message: "", priority: "normal", read: true, createdAt: "" },
      { id: "3", tenantId: "t1", type: "NEW_ORDER", title: "C", message: "", priority: "normal", read: false, createdAt: "" },
    ];

    const unreadCount = list.filter((n) => !n.read).length;
    expect(unreadCount).toBe(2);
  });

  it("updates notification read status immutably", () => {
    const list: Notification[] = [
      { id: "notif_abc", tenantId: "t1", type: "NEW_ORDER", title: "Order", message: "", priority: "normal", read: false, createdAt: "" }
    ];

    const updated = list.map((n) => (n.id === "notif_abc" ? { ...n, read: true, readAt: "2026-09-25T12:00:00Z" } : n));
    expect(updated[0].read).toBe(true);
    expect(updated[0].readAt).toBe("2026-09-25T12:00:00Z");
  });
});

describe("Email Notification Dispatch Logic and Security Invariants", () => {
  // Test simulated email handler that mirrors the edge function logic
  async function evaluateEmailDispatch(params: {
    tenantId: string;
    eventType: NotificationType;
    settingsEnabled: boolean;
    eventConfig: Record<string, { inApp: boolean; clientEmail: boolean }>;
    recipientUser?: Partial<User> | null;
    recipientEmail?: string | null;
    clientTenantId?: string | null;
    idempotencyStore: Set<string>;
    idempotencyKey?: string;
  }): Promise<{ sent: boolean; skipped: boolean; reason?: string; error?: string }> {
    // 1. Settings enabled check
    if (!params.settingsEnabled) {
      return { sent: false, skipped: true, reason: "Tenant notifications globally disabled" };
    }

    // 2. Email preference check (default OFF)
    const eventPref = params.eventConfig[params.eventType]?.clientEmail === true;
    if (!eventPref) {
      return { sent: false, skipped: true, reason: `Email notifications disabled for event ${params.eventType}` };
    }

    // 3. Recipient user status check
    if (params.recipientUser) {
      // Cross-tenant recipient check
      if (params.recipientUser.tenantId && params.recipientUser.tenantId !== params.tenantId) {
        return { sent: false, skipped: false, error: "Recipient belongs to another tenant" };
      }
      // Inactive user check
      if (params.recipientUser.status !== "ACTIVE") {
        return { sent: false, skipped: true, reason: "Recipient user is inactive" };
      }
      // Missing email check
      if (!params.recipientUser.email) {
        return { sent: false, skipped: true, reason: "Recipient user has no email address" };
      }
    }

    // 4. Missing email check
    const email = params.recipientUser?.email || params.recipientEmail;
    if (!email) {
      return { sent: false, skipped: true, reason: "No recipient email address provided" };
    }

    // 5. Cross-tenant client check
    if (params.clientTenantId && params.clientTenantId !== params.tenantId) {
      return { sent: false, skipped: false, error: "Client belongs to another tenant" };
    }

    // 6. Idempotency check
    const key = params.idempotencyKey || `${params.tenantId}_${params.eventType}_${email}`;
    if (params.idempotencyStore.has(key)) {
      return { sent: false, skipped: true, reason: "Email already sent previously (idempotent duplicate)" };
    }

    params.idempotencyStore.add(key);
    return { sent: true, skipped: false };
  }

  it("Test disabled email → no email (all 17 notification events default OFF)", async () => {
    const idempotencyStore = new Set<string>();

    for (const eventType of ALL_NOTIFICATION_TYPES) {
      const result = await evaluateEmailDispatch({
        tenantId: "tenant_alpha",
        eventType,
        settingsEnabled: true,
        eventConfig: DEFAULT_NOTIFICATION_SETTINGS, // default clientEmail: false
        recipientUser: { id: "u1", tenantId: "tenant_alpha", status: "ACTIVE", email: "user@alpha.com" },
        idempotencyStore,
      });

      expect(result.sent).toBe(false);
      expect(result.skipped).toBe(true);
      expect(result.reason).toContain("Email notifications disabled for event");
    }
  });

  it("Test enabled email → Resend request sent (all 17 notification events with opt-in)", async () => {
    const idempotencyStore = new Set<string>();

    for (const eventType of ALL_NOTIFICATION_TYPES) {
      // Opt-in enabled for this event
      const customConfig = {
        ...DEFAULT_NOTIFICATION_SETTINGS,
        [eventType]: { inApp: true, clientEmail: true },
      };

      const result = await evaluateEmailDispatch({
        tenantId: "tenant_alpha",
        eventType,
        settingsEnabled: true,
        eventConfig: customConfig,
        recipientUser: { id: `u_${eventType}`, tenantId: "tenant_alpha", status: "ACTIVE", email: `user_${eventType}@alpha.com` },
        idempotencyStore,
      });

      expect(result.sent).toBe(true);
      expect(result.skipped).toBe(false);
    }
  });

  it("Test cross-tenant recipient isolation (recipient from tenant B blocked when event is for tenant A)", async () => {
    const idempotencyStore = new Set<string>();
    const enabledConfig = {
      NEW_ORDER: { inApp: true, clientEmail: true },
    } as any;

    const result = await evaluateEmailDispatch({
      tenantId: "tenant_alpha",
      eventType: "NEW_ORDER",
      settingsEnabled: true,
      eventConfig: enabledConfig,
      // Recipient belongs to tenant_beta
      recipientUser: { id: "u_beta", tenantId: "tenant_beta", status: "ACTIVE", email: "user@beta.com" },
      idempotencyStore,
    });

    expect(result.sent).toBe(false);
    expect(result.error).toContain("Recipient belongs to another tenant");
  });

  it("Test inactive user → no notification email (skipped)", async () => {
    const idempotencyStore = new Set<string>();
    const enabledConfig = {
      NEW_ORDER: { inApp: true, clientEmail: true },
    } as any;

    const result = await evaluateEmailDispatch({
      tenantId: "tenant_alpha",
      eventType: "NEW_ORDER",
      settingsEnabled: true,
      eventConfig: enabledConfig,
      // User is INACTIVE
      recipientUser: { id: "u_inactive", tenantId: "tenant_alpha", status: "INACTIVE", email: "inactive@alpha.com" },
      idempotencyStore,
    });

    expect(result.sent).toBe(false);
    expect(result.skipped).toBe(true);
    expect(result.reason).toBe("Recipient user is inactive");
  });

  it("Test missing email → no email, but in-app notification still works", async () => {
    const idempotencyStore = new Set<string>();
    const enabledConfig = {
      ORDER_DISPATCHED: { inApp: true, clientEmail: true },
    } as any;

    // In-app notification object is created successfully
    const inAppNotification: Notification = {
      id: "notif_missing_email",
      tenantId: "tenant_alpha",
      userId: "u_no_email",
      orderId: "ord_100",
      type: "ORDER_DISPATCHED",
      title: "Order Dispatched",
      message: "Order #100 has departed the warehouse",
      priority: "normal",
      read: false,
      createdAt: new Date().toISOString(),
    };
    expect(inAppNotification.id).toBeDefined();

    // Email dispatch evaluates missing email
    const result = await evaluateEmailDispatch({
      tenantId: "tenant_alpha",
      eventType: "ORDER_DISPATCHED",
      settingsEnabled: true,
      eventConfig: enabledConfig,
      recipientUser: { id: "u_no_email", tenantId: "tenant_alpha", status: "ACTIVE", email: "" },
      idempotencyStore,
    });

    expect(result.sent).toBe(false);
    expect(result.skipped).toBe(true);
    expect(result.reason).toBe("Recipient user has no email address");
    // Verify in-app notification remains untouched and intact
    expect(inAppNotification.read).toBe(false);
    expect(inAppNotification.type).toBe("ORDER_DISPATCHED");
  });

  it("Test retry-safe and idempotent behavior: duplicate email request is ignored", async () => {
    const idempotencyStore = new Set<string>();
    const enabledConfig = {
      INVOICE_GENERATED: { inApp: true, clientEmail: true },
    } as any;

    const idempotencyKey = "inv_gen_tenant_alpha_ord_500_accountant@alpha.com";

    // 1st attempt: Sent
    const result1 = await evaluateEmailDispatch({
      tenantId: "tenant_alpha",
      eventType: "INVOICE_GENERATED",
      settingsEnabled: true,
      eventConfig: enabledConfig,
      recipientUser: { id: "u_acct", tenantId: "tenant_alpha", status: "ACTIVE", email: "accountant@alpha.com" },
      idempotencyKey,
      idempotencyStore,
    });
    expect(result1.sent).toBe(true);

    // 2nd attempt (retry with same idempotency key): Skipped as duplicate
    const result2 = await evaluateEmailDispatch({
      tenantId: "tenant_alpha",
      eventType: "INVOICE_GENERATED",
      settingsEnabled: true,
      eventConfig: enabledConfig,
      recipientUser: { id: "u_acct", tenantId: "tenant_alpha", status: "ACTIVE", email: "accountant@alpha.com" },
      idempotencyKey,
      idempotencyStore,
    });
    expect(result2.sent).toBe(false);
    expect(result2.skipped).toBe(true);
    expect(result2.reason).toContain("idempotent duplicate");
  });

  it("Test globally disabled notifications: skips all email dispatches even if event has clientEmail: true", async () => {
    const idempotencyStore = new Set<string>();
    const enabledConfig = {
      NEW_ORDER: { inApp: true, clientEmail: true },
    } as any;

    const result = await evaluateEmailDispatch({
      tenantId: "tenant_alpha",
      eventType: "NEW_ORDER",
      settingsEnabled: false, // Tenant turned off all notifications
      eventConfig: enabledConfig,
      recipientUser: { id: "u1", tenantId: "tenant_alpha", status: "ACTIVE", email: "user@alpha.com" },
      idempotencyStore,
    });

    expect(result.sent).toBe(false);
    expect(result.skipped).toBe(true);
    expect(result.reason).toBe("Tenant notifications globally disabled");
  });
});
